export default [
    {
        id: 1,
        coverImg: "Cheddar.jpg",
        country: 'United Kingdom',
        name: 'Cheddar',
        continent: 'Europe',
        description: "Cheddar cheese (or simply cheddar) is a natural cheese that is relatively hard, off-white (or orange if colourings such as annatto are added), and sometimes sharp-tasting. Cheddar originates from the English village of Cheddar in Somerset.Cheddar is the most popular cheese in the UK, accounting for 51% of the country's £1.9 billion annual cheese market.The UK produced 258,000 long tons (262,000 tonnes) in 2008.",
    },
    {
        id: 2,
        coverImg: "Jack.jpg",
        country: 'Usa',
        name: 'Monterey Jack',
        continent: 'North America',
        description: "Monterey Jack, sometimes shortened to Jack, is a US white, semi-hard cheese made using cow's milk, with a mild flavor and slight sweetness. It has been called 'an American original'.In addition to being eaten by itself, it is frequently marbled with Colby to produce Colby-Jack, or with yellow cheddar to produce cheddar-Jack. Pepper Jack is a version flavored with chili peppers and herbs. Dry Jack is a harder cheese with a longer aging time.",
    },
    {
        id: 3,
        coverImg: "Minas.jpg",
        country: 'Brasil',
        name: 'Queijo Minas',
        continent: 'South America',
        description: "Queijo Minas is a handmade cheese made from raw cow's milk, characterized by its tender, spongy texture and moistness. The flavor of Minas cheese is mild and slightly salty, depending on its ripeness and the region of production. The cheese is often used in the preparation of sandwiches, pancakes, and pastries.It is recommended to pair it with cold cuts, salads, and various vegetables that develop intense flavors after cooking.",
    },
    {
        id: 5,
        coverImg: "Camembert.jpg",
        country: 'Mexico',
        name: 'Queso Chihuahua',
        continent: 'Central America',
        description: "In Mexico, queso Chihuahua is commonly recognized as a soft white cheese available in braids, balls or rounds and originates in the Mexican state of Chihuahua. In Chihuahua and in neighboring states, it is called queso menonita, after the Mennonite communities of Northern Mexico that first produced it, while elsewhere it is called queso Chihuahua.",
    },
    {
        id: 5,
        coverImg: "Camembert.jpg",
        country: 'France',
        name: 'Camembert',
        continent: 'Europe',
        description: "Camembert is a moist, soft, creamy, surface-ripened cow's milk cheese. It was first made in the late 18th century in Camembert, Normandy, in northwest France. It is sometimes compared in look and taste to brie cheese, albeit with a slightly lower butterfat content than brie's typical 60% and 75% by weight.In 1890, an engineer, M. Ridel, devised the wooden box that was used to carry the cheese and helped to send it for longer distances. These boxes are still used today.",
    },
]